### ISSUE TITLE
Error when I warn

### ISSUE THREAD

**Issue by piitchyy** [QingyuChai/RiceCogs#14]
![image](https://cloud.githubusercontent.com/assets/17786644/24205481/cbdbb5da-0f1b-11e7-8987-3ce7c45c3fea.png)

**Comment by QingyuChai** [comment]
Welp, I'll look into it

**Comment by piitchyy** [comment]
This is the error I get in the console
```
1|Red-Bot  | [22/03/2017 17:20] ERROR red on_command_error 363: Exception in command 'warn'
1|Red-Bot  | Traceback (most recent call last):
1|Red-Bot  |   File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
1|Red-Bot  |     ret = yield from coro(*args, **kwargs)
1|Red-Bot  |   File "/home/nodeath/Red-DiscordBot/cogs/warn.py", line 300, in warn
1|Red-Bot  |     reason=reason)
1|Red-Bot  |   File "/home/nodeath/Red-DiscordBot/cogs/mod.py", line 1389, in new_case
1|Red-Bot  |     if not self.settings[server.id].get(action_type, default_settings[action_type]):
1|Red-Bot  | KeyError: 'kicked after 3 warnings._cases'
```

**Comment by piitchyy** [comment]
I updated the bot with `git pull`.
Now I get this instead
![image](https://cloud.githubusercontent.com/assets/17786644/24222843/ce2b8b02-0f53-11e7-834b-4e6195539ba3.png)

With this error in the console
```
1|Red-Bot  | [22/03/2017 22:59] ERROR red on_command_error 363: Exception in command 'warn'
1|Red-Bot  | Traceback (most recent call last):
1|Red-Bot  |   File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
1|Red-Bot  |     ret = yield from coro(*args, **kwargs)
1|Red-Bot  |   File "/home/nodeath/Red-DiscordBot/cogs/warn.py", line 296, in warn
1|Red-Bot  |     await self._cog.new_case(server,
1|Red-Bot  | AttributeError: 'NoneType' object has no attribute 'new_case'
```

**Comment by QingyuChai** [comment]
I have a temporary fix. It doesn't cooperate with modlog anymore - for now. Should be working

**Comment by piitchyy** [comment]
Yes it works :+1: 
Even tho modlog doesnt work at all after the update of the bot
